version: '3.1'

services:

  mysql:
    image: mysql:5.7.27
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: capacitaciones_tech
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "3307:3306"  